---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "vcsa.vclass.rapa"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "GUMI"
    source: "Temp-Win22-06"

  tasks:
  - name: Clone Template VM to each ESXi Hosts
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.vm }}"
      datacenter: '{{ datacenter_name }}'
      folder: "Template"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ item.datastore }}"
      template: "{{ source }}"
    loop:
      - { host: esxi-02.vclass.rapa, datastore: ESXi-02-SSD, vm: Temp-Win22-02 }
      - { host: esxi-03.vclass.rapa, datastore: ESXi-03-SSD, vm: Temp-Win22-03 }
      - { host: esxi-04.vclass.rapa, datastore: ESXi-04-SSD, vm: Temp-Win22-04 }
      - { host: esxi-05.vclass.rapa, datastore: ESXi-05-SSD, vm: Temp-Win22-05 }
    delegate_to: localhost
